### ISSUE TITLE
Contrib project pom's do not get updated on release candidate creation

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo-access#43]
When a release candidate is made for Accumulo-Access, the poms for contrib/antlr4 and contrib/getting-started do not get updated. We don't create official releases of the contrib artifacts, so I think that it's likely ok that their versions remain SNAPSHOTs. However, we might want to create a post-release action to update the version of accumulo-access that they rely on to use the newly released version.

**Comment by dlmarion** [comment]
In #44 I added issue templates and created an action in the post vote checklist to update the contrib poms. We could close this when #44 is merged if that is sufficient for resolving this issue.

**Comment by ctubbsii** [comment]
We removed contrib directory in the main project. We should try to avoid introducing them in this project.
