### ISSUE TITLE
AccessExpression.abnf could be deleted

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo-access#60]
`src/main/resources/org/apache/accumulo/access/specification/AccessExpression.abnf` exists for the sole purpose of validating that the ABNF in `SPECIFICATION.md` is valid ABNF. The contents of `AccessExpression.abnf` are a copy of the ABNF in `SPECIFICATION.md`. `AccessExpressionTest.testSpecificationDocumentation` and `AccessExpression.abnf` could be deleted and the method used in `AccessExpressionTest.testSpecificationDocumentation` to get the ABNF from `SPECIFICATION.md` could be used in `SpecificationTest`.

**Comment by ctubbsii** [comment]
I don't want to do that, because I think it's useful as a jar resource so it can be used as a dependency by other projects who might want to pull it in as the canonical definition.

**Comment by dlmarion** [comment]
ok, so that's why you added the test for equality between SPECIFICATION.md and AccessExpression.abnf. I'm fine with that, I just thought we wanted to remove the duplication.

**Comment by ctubbsii** [comment]
> ok, so that's why you added the test for equality between SPECIFICATION.md and AccessExpression.abnf. I'm fine with that, I just thought we wanted to remove the duplication.

Yes, exactly. Deduplication was my preference, but I decided to punt on that for now. We could still deduplicate by removing it from SPECIFICATION.md... but I'm not sure how much affinity people had for having it there, rather than just having a link there to the abnf file.

**Comment by ctubbsii** [comment]
I used symlinks to deduplicate the spec files in #102
